name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate the HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          blacklist: node_modules

  links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check internal links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --offline --verbose --no-progress './**/*.html' './**/*.md'
          fail: true
